server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APPLICATION_NAME:gateway-service}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # TODO: Check it!
      # For curl "http://<gateway>/some-service/predicatePath/**"
      routes:
        - id: some-service-route
          uri: lb://some-service
          predicates:
            - Path=/predicatePath/**
# Exposes http://localhost:8080/actuator/gateway/routes
# http://localhost:8080/actuator/gateway/routes/some-service-route
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: ${HOST_NAME}
    homePageUrl: http://${eureka.instance.hostname}/
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}