server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APPLICATION_NAME:gateway-service}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # TODO: Check it!
      # For curl "http://<gateway>/some-service/predicatePath/**"
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/clientService/**
          filters:
            - RewritePath=/clientService/(?<path>.*), /$\{path}
        - id: generator-service
          uri: https://generator.swagger.io/
          predicates:
            - Path=/generatorService/**
          filters:
            - RewritePath=/generatorService/(?<path>.*), /$\{path}

# Exposes http://localhost:8080/actuator/gateway/routes
# http://localhost:8080/actuator/gateway/routes/some-service-route
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: ${HOST_NAME:gateway-service-1.com}
    homePageUrl: http://${eureka.instance.hostname}/
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service-1.com:8761/eureka/}